index.js

In order to allow a single uploader to be used across multiple targets,
we need to allow URLs to be specified at runtime. So this centralizes
URL creation and provides some helper routines to clients.
@jh-bate -- it still doesn't pass that one test (which also fails on master); if you have any insights, please let me know.
I need to get this in and pushed to npm before I can make the uploader work across dev/staging/prod.

Allow changes to URLs at runtime

---

lib/common.js

simple fix to export getUploadUrl function for use

export getUploadUrl

---

confirm.js

update signupResend function as it doesn't need token, also only returns error if there is one

update resend function

---

index.js

@darinkrauss this addresses the issues seen in the chrome-uploader

Jhbate fix regressions

---

index.js

@jebeck @darinkrauss this surfaces the jellyfish endpoint for use in the uploader

Sprit 24 version check

---

README.md
test/integration/tidepoolPlatform_integration.js
tidepool.js

Final changes for new environment

---

index.js

@darinkrauss  we needed to return the body as this has the error detail we need.

Sprint26 upload errors

---

confirm.js

@darinkrauss still a WIP but some of the changes made as part or my testing

hydrophone will have set profile details already

---

confirm.js
index.js
user.js

Reverts tidepool-org/platform-client#65 since it's superseded by #66

Revert "add new custodialSignupConfirm"

---

index.js
user.js

supersedes #65 and additionally adds functions to handle creation of custodial accounts

creation and confirmation of custodial accounts

---

user.js

provide email and username to creation if provided

custodial account creation fix

---

index.js
user.js

Adding an endpoint to update custodial user accounts to support VCA adding and updating email addresses for patient accounts.

API endpoint to update a custodial user account

---

index.js
test/integration/tidepoolPlatform_integration.js

@jh-bate Remove 'api' from URL path (my mistake, should never have been in URL path); fix broken tests.
CC @gniezen

Platform updates

---

index.js
package.json
test/integration/tidepoolPlatform_integration.js

Adds the ability to save preferences and settings metadata, similar to profile metadata.

Add ability to save preferences and settings metadata

---

index.js
package.json

@jebeck associated with this https://trello.com/c/VXQ5L102

All users users

---

package.json
test/integration/tidepoolPlatform_integration.js
user.js

Add roles to fields allowed during signup

---

confirm.js
index.js
lib/common.js
package.json
test/integration/tidepoolPlatform_integration.js
user.js

The version of `superagent` needs to be updated in order to be webpack bundled in the uploader due to the use of `fs` by `node-mime` (a dependency of `superagent`). They updated their dependency as of version 1.2.0 (https://github.com/visionmedia/superagent/blob/master/History.md#120-2015-04-13). 
I haven't fully investigated the potential repercussions of this update in `blip` and need to do so before we'd update `blip`s dependency (or potentially merge this change).

WIP: Update superagent in order to be able to bundle for Electron

---

lib/common.js
package.json

Basically what it says on the tin, just updating a couple places where deep object access happens on a potentially undefined object

update object access to match the rest

---

.travis.yml
index.js
lib/id.js
package.json
test/integration/tidepoolPlatform_integration.js
user.js

@krystophv @cbwebdevelopment @pazaan Can someone give a quick review?

Support for OAuth workflow and filtering Dexcom data

---

index.js

Required for delta uploads, implemented as part of https://trello.com/c/5i0sM0wx

Getting upload records for a device

---

index.js

Returns server time from dataservices API

---

index.js
lib/common.js
package.json

See https://trello.com/c/jmYSnJCw for full details.
Goes hand in hand with:
https://github.com/tidepool-org/blip/pull/465
https://github.com/tidepool-org/viz/pull/99
https://github.com/tidepool-org/tideline/pull/328
This PR simply allows specifying the `startDate` and `endDate` query params while fetching patient diabetes data.

Data paging

---

index.js
lib/common.js
package.json

See attached Trello card for details

Upload blobs

---

package.json

Release 0.39.0

---

index.js
lib/common.js
package.json

trello: https://trello.com/c/grUQ0mcO
blip PR: https://github.com/tidepool-org/blip/pull/515

adding utilities for export service UI

---

index.js
lib/common.js
package.json

Includes:
Data Export from Tidepool for Web UI: https://trello.com/c/grUQ0mcO

Release 0.40.0

---

index.js
package.json

Needed to fix this bug: https://trello.com/c/xNVdNQ1W
Goes hand-in-hand with these PRs:
tidepool-org/blip#551
tidepool-org/tide-whisperer#58

Allow limit, sort, type, and uploadId query params on data endpoint

---

index.js
package.json

What it says on the tin. Requirement for attached Trello card.

Add device id as a possible parameter when getting device data

---

index.js
package.json

Part of [Release v1.29.0](https://tidepool.atlassian.net/projects/WEB/versions/10074/tab/release-report-all-issues)

Release 0.42.0 to master

---

index.js
package.json

Part of [Release v1.29.0](https://tidepool.atlassian.net/projects/WEB/versions/10074/tab/release-report-all-issues)

Release 0.42.0 to develop

---

.travis.yml
confirm.js
index.js
lib/common.js
package.json
user.js

Includes [WEB-829]
[WEB-829]: https://tidepool.atlassian.net/browse/WEB-829

Release 0.43.0 to master

---

index.js
lib/common.js
package.json
prescription.js

See [WEB-863] for details
Goes with tidepool-org/blip#759
[WEB-863]: https://tidepool.atlassian.net/browse/WEB-863

[WEB-863] API endpoints for prescription backend

---

clinics.js
index.js
lib/common.js
package.json

To support [WEB-834], adds in new `clinic` API endpoints.
Dependent of https://github.com/tidepool-org/blip/pull/853
[WEB-834]: https://tidepool.atlassian.net/browse/WEB-834

[WEB-834] clinics

---

index.js
package.json
prescription.js

See [WEB-1219]
Related PR: https://github.com/tidepool-org/blip/pull/937
[WEB-1219]: https://tidepool.atlassian.net/browse/WEB-1219

[WEB-1219] Update prescription API to use new clinic endpoints

---

clinics.js
index.js
package.json

See WEB-1236
Related PR: https://github.com/tidepool-org/blip/pull/940

[WEB-1236] Trigger account-to-clinic migrations

---

package.json

See  [WEB-1302].  
This branch was just used to produce a new npm build from the latest work merged to `develop` to support https://github.com/tidepool-org/blip/pull/976
[WEB-1302]: https://tidepool.atlassian.net/browse/WEB-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1302] v0.48.0-web-1302-patient-list-create-edit.1

---

package.json

Merge release 0.48.0 back to develop

Release 0.48.0 to develop

---

clinics.js
index.js
package.json

New API endpoint to support https://github.com/tidepool-org/blip/pull/1054

[WEB-1338] Add patient upload reminder api endpoint

---

clinics.js
index.js
package.json

Release candidate for [1.54.0](https://tidepool.atlassian.net/projects/WEB/versions/10226/tab/release-report-all-issues)

Release v0.49.0 to master

---

package.json

Release 0.49.0 to develop

---

clinics.js
index.js
package.json

Release v0.50.0 to master

---

package.json

Release v0.50.0 to develop

---

clinics.js
index.js
package.json

Part of [WEB-1850]
[WEB-1850]: https://tidepool.atlassian.net/browse/WEB-1850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1850] Add sendPatientDexcomConnectRequest endpoint

---

clinics.js
index.js
package.json
user.js

Release 0.51.0

---

clinics.js
index.js
package.json

[WEB-2346]
Related PR: https://github.com/tidepool-org/blip/pull/1262
[WEB-2346]: https://tidepool.atlassian.net/browse/WEB-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2346] Add endpoint to fetch tide dash patients

---

clinics.js
index.js
package.json

to support [WEB-2477] and [UPLOAD-1116]
[WEB-2477]: https://tidepool.atlassian.net/browse/WEB-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UPLOAD-1116]: https://tidepool.atlassian.net/browse/UPLOAD-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2477] mrn requirement

---

clinics.js
package.json

API endpoint updates for [WEB-2500]
Supports https://github.com/tidepool-org/blip/pull/1276
[WEB-2500]: https://tidepool.atlassian.net/browse/WEB-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2500] TIDE backend integration

---

package.json

Release 0.54.0 to master

---

clinics.js
package.json

See [WEB-2714]
Supports: https://github.com/tidepool-org/blip/pull/1331
[WEB-2714]: https://tidepool.atlassian.net/browse/WEB-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2714] Set patient MRN and other details while accepting invite to clinic

---

package.json

Release 0.55.0 to master

---

package.json

Release 0.55.0 to develop

---

clinics.js
index.js
package.json

New api endpoints to support [WEB-2763]
[WEB-2763]: https://tidepool.atlassian.net/browse/WEB-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2763] pendo patient count

---

package.json

Merge v0.57.0 to release-0.56.0

Merge v0.57.0 to release-0.56.0

---

clinics.js
package.json

Release 0.58.0 to develop

---

clinics.js
index.js
lib/common.js
package.json

[WEB-2994] [WEB-2993]
Related PRs:
---
https://github.com/tidepool-org/blip/pull/1396
https://github.com/tidepool-org/viz/pull/384
[WEB-2994]: https://tidepool.atlassian.net/browse/WEB-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2993]: https://tidepool.atlassian.net/browse/WEB-2993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2994,WEB-2993] Set patient's last reviewed on TIDE and Pop Health dashboards

---

package.json

Release 0.59.0 to develop

---

package.json
prescription.js

[WEB-3242]
Related PR: https://github.com/tidepool-org/blip/pull/1446
[WEB-3242]: https://tidepool.atlassian.net/browse/WEB-3242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3242] Increase prescriptions fetch limit

---

package.json

Release 0.60.0 to master

---

package.json

Release 0.60.0 to develop

---

clinics.js
package.json

[WEB-3178]
Related PR: https://github.com/tidepool-org/blip/pull/1459
[WEB-3178]: https://tidepool.atlassian.net/browse/WEB-3178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3178] Tide connection status

---

package.json

Release 0.61.0 to master
Related PRs
https://github.com/tidepool-org/blip/pull/1461
https://github.com/tidepool-org/viz/pull/423

Release 0.61.0 to master

---

package.json

Release 0.61.0 to develop

---

.gitignore
clinics.js
index.js
package.json

[WEB-3272](https://tidepool.atlassian.net/browse/WEB-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) [WEB-3273](https://tidepool.atlassian.net/browse/WEB-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Related PRs:
---
https://github.com/tidepool-org/blip/pull/1485
https://github.com/tidepool-org/viz/pull/429
[WEB-3272]: https://tidepool.atlassian.net/browse/WEB-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3273]: https://tidepool.atlassian.net/browse/WEB-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3272,WEB-3273] Clinician-initiated patient data connection

---

clinics.js
package.json

[WEB-3400]
[WEB-3400]: https://tidepool.atlassian.net/browse/WEB-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3400] Strip extraneous  fields from clinic patient update objects

---

.gitignore
index.js
package.json

[WEB-3396]
Related PR: https://github.com/tidepool-org/blip/pull/1543
[WEB-3396]: https://tidepool.atlassian.net/browse/WEB-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3396] Send minimum sample interval parameter for data fetches

---

.gitignore
index.js
package.json

Release 0.61.1 to master

---

index.js
package.json

- Add cbgFilter query parameter to backend API calls
- https://tidepool.atlassian.net/browse/WEB-3670

[WEB-3670] Add cbgFilter query parameter to backend API calls

---

clinics.js
package.json

https://github.com/tidepool-org/blip/pull/1717

WEB-3869 - Refetch Sites and Tags after CRUD operations 

---

consent.js
index.js
package.json

[WEB-3771]
Related PR: https://github.com/tidepool-org/blip/pull/1734
This hotfix branch was created by cherry-picking all commits from https://github.com/tidepool-org/platform-client/pull/207, being careful to exclude any merge commits from develop, and then comparing the changes in each file to make sure that no unintentional changes were carried over into this.
[WEB-3771]: https://tidepool.atlassian.net/browse/WEB-3771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3771] Informed consent hotfix
